[package]
name = "lunatic-messaging-api"
version = "0.9.0"
edition = "2021"
description = "Lunatic host functions for message sending."
homepage = "https://lunatic.solutions"
repository = "https://github.com/lunatic-solutions/lunatic/tree/main/crates/lunatic-messaging-api"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
wasmtime = "^0.38"
async-std = { version = "^1.0", features = ["attributes", "unstable"] }
tokio = { version = "^1.14", features = ["macros"] }
hash-map-id = { version = "^0.9", path = "../hash-map-id" }
lunatic-process = { version = "^0.9", path = "../lunatic-process" }
lunatic-common-api = { version = "^0.9", path = "../lunatic-common-api" }
lunatic-process-api = { version = "^0.9", path = "../lunatic-process-api" }
lunatic-networking-api = { version = "^0.9", path = "../lunatic-networking-api" }