[package]
name = "lunatic-error-api"
version = "0.1.0"
edition = "2021"
description = "Lunatic host functions that make dealing with Anyhow errors easy."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
wasmtime = "^0.35"
hash-map-id = { version = "^0.1", path = "../hash-map-id" }
lunatic-common-api = { version = "0.1", path = "../lunatic-common-api" }