[package]
name = "lunatic-process"
version = "0.1.0"
edition = "2021"
description = "Lunatic's core process, mailbox and message abstraction'"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "^0.8", features = ["v4"] }
anyhow = "^1.0"
async-std = { version = "^1.0", features = ["attributes", "unstable"] }
log = "^0.4"
tokio = { version = "^1.14", features = ["macros"] }
wasmtime = "^0.35"
serde = "^1.0"
dashmap = "5.2.0"