[package]
name = "lunatic-stdout-capture"
version = "0.10.0"
edition = "2021"
description = "Helper library for holding stdout streams of lunatic processes."
homepage = "https://lunatic.solutions"
repository = "https://github.com/lunatic-solutions/lunatic/tree/main/crates/lunatic-registry-api"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wiggle = "^0.40"
wasi-common = "^0.40"